"""create flashsale tables

Revision ID: e80ceb70e995
Revises: 5942acea8b14
Create Date: 2025-10-06 01:06:11.357705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e80ceb70e995'
down_revision: Union[str, None] = '5942acea8b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS flashsale AUTHORIZATION "user";')
    
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='flashsale'
    )
    op.create_index(op.f('ix_flashsale_orders_id'), 'orders', ['id'], unique=False, schema='flashsale')
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aggregate_type', sa.String(), nullable=False),
    sa.Column('aggregate_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='flashsale'
    )
    op.create_index(op.f('ix_flashsale_outbox_id'), 'outbox', ['id'], unique=False, schema='flashsale')
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='flashsale'
    )
    op.create_index(op.f('ix_flashsale_payment_id'), 'payment', ['id'], unique=False, schema='flashsale')
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='flashsale'
    )
    op.create_index(op.f('ix_flashsale_product_id'), 'product', ['id'], unique=False, schema='flashsale')
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='flashsale'
    )
    op.create_index(op.f('ix_flashsale_reservation_id'), 'reservation', ['id'], unique=False, schema='flashsale')
    op.create_table('inventory',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['flashsale.product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id'),
    schema='flashsale'
    )
    op.drop_index('ix_outbox_id', table_name='outbox')
    op.drop_table('outbox')
    op.drop_table('inventory')
    op.drop_index('ix_product_id', table_name='product')
    op.drop_table('product')
    op.drop_index('ix_reservation_id', table_name='reservation')
    op.drop_table('reservation')
    op.drop_index('ix_payment_id', table_name='payment')
    op.drop_table('payment')
    op.drop_index('ix_orders_id', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP SCHEMA IF EXISTS flashsale CASCADE;')
    
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='orders_pkey')
    )
    op.create_index('ix_orders_id', 'orders', ['id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='payment_pkey')
    )
    op.create_index('ix_payment_id', 'payment', ['id'], unique=False)
    op.create_table('reservation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('create_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='reservation_pkey')
    )
    op.create_index('ix_reservation_id', 'reservation', ['id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('product_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='product_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_product_id', 'product', ['id'], unique=False)
    op.create_table('inventory',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reserved', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('available', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='inventory_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', name='inventory_pkey')
    )
    op.create_table('outbox',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('aggregate_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('aggregate_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payload_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='outbox_pkey')
    )
    op.create_index('ix_outbox_id', 'outbox', ['id'], unique=False)
    op.drop_table('inventory', schema='flashsale')
    op.drop_index(op.f('ix_flashsale_reservation_id'), table_name='reservation', schema='flashsale')
    op.drop_table('reservation', schema='flashsale')
    op.drop_index(op.f('ix_flashsale_product_id'), table_name='product', schema='flashsale')
    op.drop_table('product', schema='flashsale')
    op.drop_index(op.f('ix_flashsale_payment_id'), table_name='payment', schema='flashsale')
    op.drop_table('payment', schema='flashsale')
    op.drop_index(op.f('ix_flashsale_outbox_id'), table_name='outbox', schema='flashsale')
    op.drop_table('outbox', schema='flashsale')
    op.drop_index(op.f('ix_flashsale_orders_id'), table_name='orders', schema='flashsale')
    op.drop_table('orders', schema='flashsale')
    # ### end Alembic commands ###
